### ISSUE TITLE
Log poisoning

### ISSUE THREAD

**Issue by pvencill** [Monwara/node-logging#2]
This is a really cool library; easy to use and well designed. One thing I'd like to see added, though, is protection in the log() function against log poisoning / tampering.  i.e. sanitize the msg variable (and anything else coming in) so that it doesn't add newlines or other things that could potentially mess with the log file.

**Comment by foxbunny** [comment]
Yeah, that's a good idea. I'll look into it as soon as I have some time.

**Comment by foxbunny** [comment]
@pvencill Any input on this? I've looked around for different log poisoning techniques people use, but it's usually along the lines of "IF you read your log files in PHP scripts running on Apache, etc etc". Couldn't find anything generic that would work in this case.

As for simple cleanup of the log files, I will make it optional, because sometimes I do want newlines and everything else logged. Of course, still quite busy, and still not needing this functionality myself, so I'll have to postpone it.

**Comment by pvencill** [comment]
Sorry for the delayed response.  Most of the best practice stuff I've seen on it involves encoding, escaping or stripping anything that might be unsafe input.  The simplest way is probably to assume that the actual log message passed should by default only include a-zA-Z0-9, and so you encode, escape, or strip anything else.  Then, through an options object of some kind, let the consuming code provide an alternate regex, or possibly an array of safe characters.  Fancier still would be to allow the consuming code to likewise choose what sanitization method desired, etc.  I might have some time in the next couple weeks between trips, if so I'll give it a shot on a fork.

**Comment by foxbunny** [comment]
Ok, thanks.

**Comment by foxbunny** [comment]
Meanwhile, let me suggest a solution. I could make two configuration options. One would be 'blacklist', and other would be (well, you've guessed it), 'whitelist'. Both would be an array of regexes, which would be used to clean up the parameter values and log messages. If whitelist is specified, blacklist is ignored (whitelists always take precedence).

Also, remember that at one point in the code, I check whether a field is called 'password'? This is stored in an array called 'EXCLUDES', which can be set using the `setExcludes()` call. The API for setting whitelists and blacklists would be the same.

So, instead of forcing a predefined solution on users, let's make this configurable in a more generic way.

**Comment by foxbunny** [comment]
@pvencill Please check out the [blacklist](https://github.com/HerdHound/node-logging/tree/blacklist) branch, and see examples. See if you can use that.

EDIT: If that does what you need, we can add various configuration examples to the README file, and describe their purpose there.

EDIT 2: The express middleware versions of the logging method are not using white- and blacklists atm. I'll implement those if and when we agree this is the correct solution.

**Comment by pvencill** [comment]
I think that's a great solution, thanks for implementing it so quickly!

**Comment by foxbunny** [comment]
Sorry for delayed response. I'll merge this into master soon, with docs and express middleware fix. Please be patient.

**Comment by foxbunny** [comment]
Fixed in 0.1.4
